### ISSUE TITLE
checking whether genomicsdb works... configure: error: GenomicsDB installation at /opt/GenomicsDB/ is not functional

### ISSUE THREAD

**Issue by lima1** [nalinigans/GenomicsDB-R#17]
Hi @nalinigans ,

I think this happens due to the recent deprecation of genomics_db_version, although my naive attempt in fixing it by replacing it with genomicsdb::version().size > 0 did not work.

Thanks again,
Markus

**Comment by nalinigans** [comment]
It is indeed replaced by `genomicsdb::version()` which returns `std::string`. So, you may have to do a `genomicsdb::version().size()`. 

I had forgotten to merge my changes from the `develop` branch to `master`. Sorry for the oversight. See https://github.com/GenomicsDB/GenomicsDB-R/blob/f3c8a897ce621b557f354390aebb03b20e40209b/src/genomicsdb_query.cpp#L87

Let me know if you are still seeing the issue.

**Comment by lima1** [comment]
I think the particular configure check fails here: https://github.com/GenomicsDB/GenomicsDB-R/blob/master/configure.ac#L76C1-L86C106. 

I tried it with both develop and master for GenomicsDB and GenomicsDB-R. Does installing GenomicsDB-R work for you? Then maybe my GenomicsDB is indeed not functional.

**Comment by nalinigans** [comment]
Just merged from develop into master and see that the GitHub Actions has failed. Just started looking at the failure, hopefully will get in a fix soon.

**Comment by nalinigans** [comment]
@lima1, seems to be fixed now. Please reopen if you still see issues. Thanks.
